apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux101-web
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: linux101-web
  template:
    metadata:
      labels:
        app: linux101-web
        web: linux101
        version: "1.3.4"
    spec:
      containers:
      - name: web
        image: feliperibeiro95/linux101-web:1.3.4
        env:
        - name: VERSION
          value: "1.3.4"
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - wget
            - "-T2"
            - "-O-"
            - linux101-web:80
